### ISSUE TITLE
Force wifi

### ISSUE THREAD

**Issue by ghost** [studioidan/HttpAgent#5]
Hey! I'm trying to create an app to login to a wifi hotspot but I have a problem, when I want to submit the form the mobile data is used because the wifi connection is not "working" until you submit the form. With your library can I choose to use wifi connection to post the form instead of mobile data? 

Thanks!

**Comment by studioidan** [comment]
hi.. in order to fore wifi connection you can use NetworkRequest.
here is an example:

ConnectivityManager connection_manager = (ConnectivityManager) getActivity().getApplication().getSystemService(Context.CONNECTIVITY_SERVICE);
        NetworkRequest.Builder request = null;
        request = new NetworkRequest.Builder();
        request.addTransportType(NetworkCapabilities.TRANSPORT_WIFI);
        if (connection_manager == null) return;
        connection_manager.registerNetworkCallback(request.build(), new ConnectivityManager.NetworkCallback() {
            @RequiresApi(api = Build.VERSION_CODES.LOLLIPOP)
            @Override
            public void onAvailable(Network network) {
                ConnectivityManager.setProcessDefaultNetwork(network);
            }
        });


have fun....
